### PR TITLE
Fix marking unmarking appointment shift order

### LINKED ISSUE #130: Marking and Unmarking of Appointments shifts order of existing appointments
The order of appointments will shift within the list after marking appointment commands.

### PR DESCRIPTION
**Pull request by mervyn-teo**
Fix #130

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -272,7 +270,7 @@ public void markAppointmentVisited(Person target, Appointment apptToMark) {
     public void unmarkAppointmentVisited(Person target, Appointment apptToUnmark) {
         requireAllNonNull(target, apptToUnmark);
 
-        Appointment visited = new Appointment(
+        Appointment unvisited = new Appointment(
```
Comment (DiligentPenguinn) [inline src/main/java/seedu/address/model/ModelManager.java:273]: Maybe noun names are clearer? (unvisitedAppointment)

Comment (mervyn-teo) [reply src/main/java/seedu/address/model/ModelManager.java]: Sounds good! i will fix it

File: src/main/java/seedu/address/model/appointment/AppointmentListByDate.java [hunk 2]
```diff
@@ -121,4 +123,33 @@ public void deleteAppointment(Appointment appointmentToDelete) {
...
+     * Replaces the target appointment with the edited appointment.
+     * If the target appointment does not exist, an AppointmentNotFoundException is thrown.
+     * If the edited appointment overlaps with another appointment, an OverlappingAppointmentException is thrown.
+     *
+     * @param target the appointment to be replaced
+     * @param editedAppointment the appointment to replace the target appointment
+     * @throws AppointmentNotFoundException if the target appointment does not exist
+     * @throws OverlappingAppointmentException if the edited appointment overlaps with another appointment
+     */
+    public void replaceAppointment(Appointment target, Appointment editedAppointment) {
```
Comment (awlarpi) [inline src/main/java/seedu/address/model/appointment/AppointmentListByDate.java:137]: nice refactoring!

**Review by awlarpi — APPROVED** [review]
LGTM
