### PR TITLE
Fix issue where inputs in various commands can be set to an invalid date

### LINKED ISSUE #140: Setting the Startdate of an appointment to Feb 31 will be set to Feb 28
Setting the Startdate of an appointment to Feb 31 will be set to Feb 28, this should produce an error instead.

### LINKED ISSUE #141: Setting the date of appton command to Feb 31 will be set to Feb 28
Image
Setting the date of appton command to Feb 31 will be set to Feb 28

### PR DESCRIPTION
**Pull request by mervyn-teo**
Fix issue where inputs in various commands can be set to an invalid date (Feb 31st)
Resolves #140 #141 #144

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewAppointmentByDateParser.java [hunk 1]
```diff
@@ -24,11 +24,10 @@ public ViewAppointmentByDateCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
                     ViewAppointmentByDateCommand.MESSAGE_USAGE));
         }
-        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
         LocalDate date = LocalDate.now();
 
         try {
-            date = LocalDate.parse(argMultimap.getValue(PREFIX_DATE).get(), formatter);
+            date = LocalDate.parse(argMultimap.getValue(PREFIX_DATE).get(), DateUtil.getDateFormatter());
```
Comment (zhenglong1603) [inline src/main/java/seedu/address/logic/parser/ViewAppointmentByDateParser.java:30]: maybe can try import
import static seedu.address.commons.util.DateUtil.DATE_FORMATTER;

**Review by zhenglong1603 — APPROVED** [review]
